
# https://github.com/casey/just

default:
    @just --list

#     cabal run adventOfCode2021 -- $(day) $(part) $(useExample)
run day='01' part='1' useExample='0':
    cabal run aoc2022 -- {{day}} {{part}} {{useExample}}


get day='01':
    aoc download -d {{day}} -I -i ./app/Day{{day}}/in