
# https://github.com/casey/just

default:
    @just --list

#     cabal run adventOfCode2021 -- $(day) $(part) $(useExample)
run day='01' part='1' useExample='0':
    cabal run aoc2022 -- {{day}} {{part}} {{useExample}}
